export type Job = {
  id: string
  title: string
  company: string
  location: string
  mode: 'Remote' | 'Hybrid' | 'Onsite'
  experience: 'Fresher' | '0-1' | '1-3' | '3-5'
  skills: string[]
  source: 'LinkedIn' | 'Naukri' | 'Indeed'
  postedDaysAgo: number
  salaryRange: string
  applyUri: string
  description: string
}

export const jobs: Job[] = [
  {
    id: 'job-1',
    title: 'SDE Intern',
    company: 'Amazon India',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'Data Structures', 'Algorithms', 'Problem Solving'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.amazon.jobs/en/jobs/example-sde-intern-blr',
    description:
      'Work with an experienced engineering team on high-scale services used across Amazon India.\nCollaborate on design discussions, code reviews, and feature rollouts.\nIdeal for final-year students with strong fundamentals in algorithms and object-oriented design.',
  },
  {
    id: 'job-2',
    title: 'Graduate Engineer Trainee',
    company: 'Infosys',
    location: 'Mysuru, Karnataka',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'SQL', 'Spring Boot', 'REST APIs'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '3-5 LPA',
    applyUri: 'https://careers.infosys.com/graduate-engineer-trainee',
    description:
      'Join Infosys as a Graduate Engineer Trainee and rotate across multiple project teams.\nContribute to enterprise applications in banking, retail, and manufacturing domains.\nStructured training and mentoring provided during the first six months.',
  },
  {
    id: 'job-3',
    title: 'Frontend Intern',
    company: 'Flipkart',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['JavaScript', 'React', 'HTML', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.flipkartcareers.com/#!/job/frontend-intern',
    description:
      'Build interface components for high-traffic e-commerce flows at Flipkart.\nWork closely with senior engineers to translate Figma designs into reliable React components.\nExposure to performance optimization and A/B testing frameworks.',
  },
  {
    id: 'job-4',
    title: 'Junior Backend Developer',
    company: 'Razorpay',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Node.js', 'PostgreSQL', 'REST APIs', 'Microservices'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '6-10 LPA',
    applyUri: 'https://razorpay.com/careers/jobs/junior-backend-developer',
    description:
      'Contribute to payment APIs that power merchants across India.\nParticipate in design reviews, incident retrospectives, and performance tuning.\nIdeal for engineers with hands-on experience in Node.js and relational databases.',
  },
  {
    id: 'job-5',
    title: 'Data Analyst Intern',
    company: 'Swiggy',
    location: 'Bangalore, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Tableau', 'Python'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.swiggy.com/jobs/data-analyst-intern',
    description:
      'Support city operations by analysing order patterns and delivery times.\nBuild simple dashboards and reports to help teams make better decisions.\nGood role for students with strong analytical skills and curiosity about consumer data.',
  },
  {
    id: 'job-6',
    title: 'Java Developer (0-1)',
    company: 'TCS',
    location: 'Pune, Maharashtra',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Core Java', 'Spring Boot', 'REST', 'Git'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '3-5 LPA',
    applyUri: 'https://ibegin.tcs.com/java-developer-entry',
    description:
      'Work on enterprise-grade backend services for global clients.\nFollow established coding standards, documentation practices, and review processes.\nSuitable for engineers who enjoy working on predictable, large-scale systems.',
  },
  {
    id: 'job-7',
    title: 'Python Developer (Fresher)',
    company: 'Wipro',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'REST APIs', 'Git'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '3-5 LPA',
    applyUri: 'https://careers.wipro.com/python-developer-fresher',
    description:
      'Join a small team building internal tools using Django and REST APIs.\nYou will work on well-scoped tickets with clear acceptance criteria.\nIdeal for freshers comfortable with Python basics and web frameworks.',
  },
  {
    id: 'job-8',
    title: 'React Developer (1-3)',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'HTML', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '6-10 LPA',
    applyUri: 'https://careers.zoho.com/jobs/react-developer',
    description:
      'Implement front-end features across Zoho’s SaaS products.\nCollaborate with product designers and backend engineers for smooth releases.\nGood fit for developers who like clean UI, accessibility, and performance.',
  },
  {
    id: 'job-9',
    title: 'QA Intern',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Manual Testing', 'Test Cases', 'Basic SQL'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.freshworks.com/company/careers/qa-intern',
    description:
      'Help maintain product quality by executing regression suites.\nWork with senior QA engineers to improve test coverage for critical flows.\nSuitable for students interested in product testing and quality processes.',
  },
  {
    id: 'job-10',
    title: 'SDE Intern',
    company: 'CRED',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Go', 'Microservices', 'Kubernetes', 'Distributed Systems'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.cred.club/jobs/sde-intern',
    description:
      'Work on backend systems that power CRED’s consumer experiences.\nYou will pair with experienced engineers and ship small but meaningful improvements.\nIdeal for candidates who enjoy learning from high-quality codebases.',
  },
  {
    id: 'job-11',
    title: 'Graduate Engineer Trainee',
    company: 'Capgemini',
    location: 'Mumbai, Maharashtra',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'Spring', 'SQL', 'JUnit'],
    source: 'Naukri',
    postedDaysAgo: 8,
    salaryRange: '3-5 LPA',
    applyUri: 'https://www.capgemini.com/in-en/careers/graduate-engineer-trainee',
    description:
      'Join a structured graduate program with clear learning paths.\nYou will contribute to client implementations under close guidance.\nPerformance and consistency matter more than flashy output.',
  },
  {
    id: 'job-12',
    title: 'Junior Backend Developer',
    company: 'PhonePe',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'MySQL', 'Kafka'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '10-18 LPA',
    applyUri: 'https://www.phonepe.com/careers/junior-backend-developer',
    description:
      'Contribute to transaction processing systems with strict reliability requirements.\nParticipate in incident analysis and gradual performance improvements.\nIdeal for developers who prefer depth over breadth in backend engineering.',
  },
  {
    id: 'job-13',
    title: 'Data Analyst Intern',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Power BI'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://jobs.paytm.com/data-analyst-intern',
    description:
      'Assist business teams with regular reporting and ad-hoc analysis.\nYou will work on well-defined data pulls and chart creation.\nExposure to digital payments data and customer funnel metrics.',
  },
  {
    id: 'job-14',
    title: 'Java Developer (0-1)',
    company: 'Cognizant',
    location: 'Kochi, Kerala',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'Spring MVC', 'Oracle DB'],
    source: 'Naukri',
    postedDaysAgo: 9,
    salaryRange: '3-5 LPA',
    applyUri: 'https://careers.cognizant.com/java-developer-kochi',
    description:
      'Support maintenance and incremental enhancements for existing enterprise systems.\nFollow ticket-based workflows with clear priorities and timelines.\nSuitable for engineers looking for stable, process-driven environments.',
  },
  {
    id: 'job-15',
    title: 'React Developer (1-3)',
    company: 'Juspay',
    location: 'Bangalore, Karnataka',
    mode: 'Remote',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Redux', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10-18 LPA',
    applyUri: 'https://juspay.in/careers/react-developer',
    description:
      'Work on merchant-facing dashboards and internal tooling for payment operations.\nYou will implement features carefully, with attention to performance and clarity.\nExpect close collaboration with design and product teams.',
  },
  {
    id: 'job-16',
    title: 'SDE Intern',
    company: 'Razorpay',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'Spring Boot', 'PostgreSQL'],
    source: 'Indeed',
    postedDaysAgo: 0,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://razorpay.com/careers/sde-intern-payments',
    description:
      'Assist with the development of internal APIs and tooling for finance teams.\nYou will receive manageable scopes and frequent feedback.\nIdeal for interns who want exposure to fintech engineering with clear boundaries.',
  },
  {
    id: 'job-17',
    title: 'Graduate Engineer Trainee',
    company: 'IBM India',
    location: 'Pune, Maharashtra',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Cloud Basics', 'Git'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '3-5 LPA',
    applyUri: 'https://www.ibm.com/in-en/employment/graduate-trainee',
    description:
      'Join IBM’s early professional program and work across different internal products.\nYou will be expected to learn steadily and communicate clearly.\nA good option for engineers who value structure and predictability.',
  },
  {
    id: 'job-18',
    title: 'Frontend Intern',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['JavaScript', 'Vue.js', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.freshworks.com/company/careers/frontend-intern',
    description:
      'Build small UI features across Freshworks products under close review.\nYou will work on component libraries, bug fixes, and accessibility improvements.\nIdeal for interns who enjoy structured feedback and design consistency.',
  },
  {
    id: 'job-19',
    title: 'Junior Backend Developer',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Java', 'MySQL', 'REST', 'Linux'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '6-10 LPA',
    applyUri: 'https://careers.zoho.com/jobs/junior-backend',
    description:
      'Contribute to internal services that support Zoho’s product suite.\nYou will be expected to write clear, maintainable code and tests.\nGreat for developers who prefer long-term ownership of modules.',
  },
  {
    id: 'job-20',
    title: 'Data Analyst Intern',
    company: 'Flipkart',
    location: 'Bangalore, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Pandas'],
    source: 'Indeed',
    postedDaysAgo: 7,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.flipkartcareers.com/#!/job/data-analyst-intern',
    description:
      'Work with analytics teams to monitor experiments and operational metrics.\nYou will write SQL queries, clean datasets, and summarize findings.\nSuited for interns who enjoy careful, methodical data work.',
  },
  {
    id: 'job-21',
    title: 'Python Developer (Fresher)',
    company: 'Accenture India',
    location: 'Gurgaon, Haryana',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Flask', 'APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 8,
    salaryRange: '3-5 LPA',
    applyUri: 'https://www.accenture.com/in-en/careers/python-developer-fresher',
    description:
      'Join a delivery team building internal dashboards and automation scripts.\nWork with senior developers on clearly defined modules.\nIdeal for freshers comfortable with basic web development in Python.',
  },
  {
    id: 'job-22',
    title: 'React Developer (1-3)',
    company: 'PhonePe',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Redux'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10-18 LPA',
    applyUri: 'https://www.phonepe.com/careers/react-developer',
    description:
      'Build merchant configuration panels and internal tools for support teams.\nYou will iterate calmly with design and product based on measured outcomes.\nBest suited for developers who like stability and clear expectations.',
  },
  {
    id: 'job-23',
    title: 'SDE Intern',
    company: 'CRED',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Node.js', 'TypeScript', 'PostgreSQL'],
    source: 'Naukri',
    postedDaysAgo: 2,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.cred.club/jobs/sde-intern-platform',
    description:
      'Support platform teams by picking up smaller enhancements and bug fixes.\nYou will work on internal tools first and gradually move to user-facing flows.\nGood for interns who prefer depth over breadth.',
  },
  {
    id: 'job-24',
    title: 'Graduate Engineer Trainee',
    company: 'Oracle India',
    location: 'Bangalore, Karnataka',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'Oracle DB', 'PL/SQL'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '3-5 LPA',
    applyUri: 'https://oracle.taleo.net/graduate-engineer-trainee',
    description:
      'Join a team building and maintaining Oracle enterprise products.\nYou will learn established engineering practices and deployment processes.\nSuitable for engineers comfortable with relational databases and server-side code.',
  },
  {
    id: 'job-25',
    title: 'Frontend Intern',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['JavaScript', 'React', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://jobs.paytm.com/frontend-intern',
    description:
      'Help implement UI improvements across Paytm web flows.\nYou will work on A/B experiments and bug fixes with clear owners.\nIdeal for interns who enjoy shipping small, frequent improvements.',
  },
  {
    id: 'job-26',
    title: 'Junior Backend Developer',
    company: 'SAP Labs India',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Java', 'Spring', 'Microservices'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '10-18 LPA',
    applyUri: 'https://jobs.sap.com/junior-backend-developer',
    description:
      'Contribute to backend services that support SAP cloud products.\nYou will work on well-defined stories with clear acceptance criteria.\nBest for developers who prefer working within established architectures.',
  },
  {
    id: 'job-27',
    title: 'Data Analyst Intern',
    company: 'Razorpay',
    location: 'Bangalore, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Looker', 'Excel'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://razorpay.com/careers/data-analyst-intern',
    description:
      'Support business teams with recurring dashboards and ad-hoc reports.\nYou will learn how to ask clear questions before diving into data.\nIdeal for interns who prefer methodical, well-scoped analysis.',
  },
  {
    id: 'job-28',
    title: 'Python Developer (Fresher)',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'Flask', 'MySQL'],
    source: 'Indeed',
    postedDaysAgo: 7,
    salaryRange: '3-5 LPA',
    applyUri: 'https://careers.zoho.com/jobs/python-developer-fresher',
    description:
      'Work on internal automation and simple web services.\nYou will own small modules end-to-end with supervision.\nA good role for freshers who value clarity and consistent routines.',
  },
  {
    id: 'job-29',
    title: 'React Developer (1-3)',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Sass'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '6-10 LPA',
    applyUri: 'https://www.freshworks.com/company/careers/react-engineer',
    description:
      'Help maintain and extend the front-end for customer support products.\nYou will work iteratively, shipping incremental UI changes.\nBest for engineers who like predictable, well-reviewed workflows.',
  },
  {
    id: 'job-30',
    title: 'SDE Intern',
    company: 'Infosys',
    location: 'Mysuru, Karnataka',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Spring Boot', 'SQL'],
    source: 'Naukri',
    postedDaysAgo: 0,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.infosys.com/sde-intern',
    description:
      'Assist project teams with clearly-scoped development tasks.\nYou will be provided with training, documentation, and sample code.\nGood for students who want gradual exposure to production systems.',
  },
  {
    id: 'job-31',
    title: 'Graduate Engineer Trainee',
    company: 'Dell Technologies',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['C++', 'Linux', 'Networking Basics'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '3-5 LPA',
    applyUri: 'https://jobs.dell.com/graduate-engineer-trainee',
    description:
      'Join Dell’s engineering team working on server and storage software.\nYou will work with mentors on low-risk features and bug fixes.\nIdeal for engineers who want exposure to systems programming.',
  },
  {
    id: 'job-32',
    title: 'Frontend Intern',
    company: 'Razorpay',
    location: 'Bangalore, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['React', 'TypeScript', 'CSS Modules'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://razorpay.com/careers/frontend-intern',
    description:
      'Contribute to internal tools used by operations and finance teams.\nYou will work with existing component libraries and design tokens.\nIdeal for interns who value consistency and clear design guidelines.',
  },
  {
    id: 'job-33',
    title: 'Junior Backend Developer',
    company: 'Capgemini',
    location: 'Pune, Maharashtra',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'Docker'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '6-10 LPA',
    applyUri: 'https://www.capgemini.com/in-en/careers/junior-backend-developer',
    description:
      'Support implementation and maintenance of microservices for enterprise clients.\nYou will follow established CI/CD practices and documentation standards.\nBest for developers who value structure and reliable tooling.',
  },
  {
    id: 'job-34',
    title: 'Data Analyst Intern',
    company: 'Amazon India',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Redshift', 'Excel'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.amazon.jobs/en/jobs/example-data-analyst-intern',
    description:
      'Work with retail analytics teams on demand forecasting and inventory insights.\nYou will create and maintain clearly documented queries.\nIdeal for interns who prefer careful, repeatable analysis.',
  },
  {
    id: 'job-35',
    title: 'Python Developer (Fresher)',
    company: 'Infosys',
    location: 'Pune, Maharashtra',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'REST'],
    source: 'Indeed',
    postedDaysAgo: 7,
    salaryRange: '3-5 LPA',
    applyUri: 'https://careers.infosys.com/python-developer-fresher',
    description:
      'Develop and maintain internal dashboards and automation workflows.\nYou will work from clearly defined specifications and wireframes.\nGood for freshers who appreciate predictable project plans.',
  },
  {
    id: 'job-36',
    title: 'React Developer (1-3)',
    company: 'Flipkart',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'Redux', 'TypeScript'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '10-18 LPA',
    applyUri: 'https://www.flipkartcareers.com/#!/job/react-developer',
    description:
      'Build and maintain UI flows for checkout, payments, and post-order experiences.\nYou will focus on clarity, performance, and reliability over flashy effects.\nIdeal for engineers comfortable with incremental improvements.',
  },
  {
    id: 'job-37',
    title: 'SDE Intern',
    company: 'Swiggy',
    location: 'Bangalore, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['Java', 'Kotlin', 'REST'],
    source: 'Naukri',
    postedDaysAgo: 1,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.swiggy.com/jobs/sde-intern-android',
    description:
      'Work with the Android team on internal tools and supporting libraries.\nYou will primarily handle non-critical features and bug fixes.\nGood for interns who prefer small, well-defined tasks.',
  },
  {
    id: 'job-38',
    title: 'Graduate Engineer Trainee',
    company: 'Wipro',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'SQL', 'Basic Cloud'],
    source: 'Indeed',
    postedDaysAgo: 8,
    salaryRange: '3-5 LPA',
    applyUri: 'https://careers.wipro.com/graduate-trainee',
    description:
      'Rotate across multiple client projects with clear supervision.\nYou will focus on implementation rather than architecture in the first year.\nSuitable for engineers who like gradual exposure to complexity.',
  },
  {
    id: 'job-39',
    title: 'Frontend Intern',
    company: 'CRED',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['React', 'TypeScript', 'Styled Components'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.cred.club/jobs/frontend-intern',
    description:
      'Help maintain internal admin panels used by operations teams.\nYou will work with an existing design system and component library.\nIdeal for interns who value well-defined scopes and code reviews.',
  },
  {
    id: 'job-40',
    title: 'Junior Backend Developer',
    company: 'Razorpay',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['Go', 'PostgreSQL', 'gRPC'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '10-18 LPA',
    applyUri: 'https://razorpay.com/careers/junior-backend-go',
    description:
      'Work on internal settlement and reconciliation services.\nYou will implement features carefully with a focus on correctness.\nGood for developers who are comfortable reading existing code before changing it.',
  },
  {
    id: 'job-41',
    title: 'Data Analyst Intern',
    company: 'PhonePe',
    location: 'Bangalore, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Dashboards'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.phonepe.com/careers/data-analyst-intern',
    description:
      'Support product analytics by tracking feature adoption and funnels.\nYou will build charts and summaries that are reused in reviews.\nBest for interns who like recurring, structured analysis tasks.',
  },
  {
    id: 'job-42',
    title: 'Python Developer (Fresher)',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Flask', 'MySQL'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '3-5 LPA',
    applyUri: 'https://www.freshworks.com/company/careers/python-engineer-fresher',
    description:
      'Work on back-office automation tools and reporting utilities.\nYou will iterate gradually, focusing on clarity and maintainability.\nIdeal for freshers who prefer predictable, well-scoped tasks.',
  },
  {
    id: 'job-43',
    title: 'React Developer (1-3)',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'Redux', 'TypeScript'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '6-10 LPA',
    applyUri: 'https://jobs.paytm.com/react-developer',
    description:
      'Implement and refine UI flows for wallet, UPI, and bill payments.\nYou will focus on clarity, load time, and accessibility.\nBest for engineers who like stable, iterative work.',
  },
  {
    id: 'job-44',
    title: 'SDE Intern',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['C++', 'Java', 'Data Structures'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.zoho.com/jobs/sde-intern',
    description:
      'Support the engineering team with internal tools and utility libraries.\nYou will work from clear problem statements and sample implementations.\nGood fit for students who enjoy core programming.',
  },
  {
    id: 'job-45',
    title: 'Graduate Engineer Trainee',
    company: 'Amazon India',
    location: 'Hyderabad, Telangana',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Data Structures', 'AWS Basics'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '6-10 LPA',
    applyUri: 'https://www.amazon.jobs/en/jobs/example-graduate-engineer',
    description:
      'Work with an Amazon engineering team on internal tools and reporting.\nYou will start with less risky changes before moving to critical paths.\nIdeal for graduates who want to grow steadily in a large organisation.',
  },
  {
    id: 'job-46',
    title: 'Frontend Intern',
    company: 'SAP Labs India',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['JavaScript', 'UI5', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://jobs.sap.com/frontend-intern',
    description:
      'Assist teams building enterprise UIs using SAP UI5.\nYou will follow clear design specifications and coding guidelines.\nGood for interns who are comfortable working with design systems.',
  },
  {
    id: 'job-47',
    title: 'Junior Backend Developer',
    company: 'Infosys',
    location: 'Mysuru, Karnataka',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Java', 'Spring Boot', 'REST', 'SQL'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '6-10 LPA',
    applyUri: 'https://careers.infosys.com/junior-backend-developer',
    description:
      'Support enterprise backend services with incremental improvements.\nYou will focus on reliability, logging, and small enhancements.\nBest for developers who appreciate gradual growth in responsibility.',
  },
  {
    id: 'job-48',
    title: 'Data Analyst Intern',
    company: 'Cognizant',
    location: 'Pune, Maharashtra',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Power BI'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.cognizant.com/data-analyst-intern',
    description:
      'Assist with reporting and dashboards for global clients.\nYou will follow clear templates and guidelines for data presentation.\nIdeal for interns who like structured tasks and consistent routines.',
  },
  {
    id: 'job-49',
    title: 'Python Developer (Fresher)',
    company: 'Capgemini',
    location: 'Mumbai, Maharashtra',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'REST'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '3-5 LPA',
    applyUri: 'https://www.capgemini.com/in-en/careers/python-developer-fresher',
    description:
      'Work on internal web applications for support and operations teams.\nYou will operate within existing architectures and coding guidelines.\nSuitable for freshers who like stable workstreams.',
  },
  {
    id: 'job-50',
    title: 'React Developer (1-3)',
    company: 'Swiggy',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '6-10 LPA',
    applyUri: 'https://careers.swiggy.com/jobs/react-developer',
    description:
      'Build and refine tools used by restaurant and delivery partners.\nYou will work with clear product requirements and stable design libraries.\nBest for engineers who enjoy incremental UX improvements.',
  },
  {
    id: 'job-51',
    title: 'SDE Intern',
    company: 'PhonePe',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'Spring', 'MySQL'],
    source: 'Naukri',
    postedDaysAgo: 8,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.phonepe.com/careers/sde-intern',
    description:
      'Support backend teams on internal tooling and simple service enhancements.\nYou will start with low-risk tasks and gradually take more ownership.\nIdeal for interns comfortable with learning by reading code.',
  },
  {
    id: 'job-52',
    title: 'Graduate Engineer Trainee',
    company: 'IBM India',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Cloud Basics', 'Git'],
    source: 'Indeed',
    postedDaysAgo: 9,
    salaryRange: '3-5 LPA',
    applyUri: 'https://www.ibm.com/in-en/employment/graduate-trainee-blr',
    description:
      'Participate in IBM’s structured graduate program with rotations.\nYou will build confidence by working on predictable, well-documented tasks.\nGood for engineers who value stability and mentoring.',
  },
  {
    id: 'job-53',
    title: 'Frontend Intern',
    company: 'Paytm',
    location: 'Noida, Uttar Pradesh',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['HTML', 'CSS', 'JavaScript'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://jobs.paytm.com/frontend-intern-web',
    description:
      'Support marketing and growth teams with landing page updates.\nYou will work from Figma designs and copy documents.\nBest for interns who like clear before/after definitions.',
  },
  {
    id: 'job-54',
    title: 'Junior Backend Developer',
    company: 'Oracle India',
    location: 'Hyderabad, Telangana',
    mode: 'Onsite',
    experience: '1-3',
    skills: ['Java', 'Oracle DB', 'REST'],
    source: 'Naukri',
    postedDaysAgo: 2,
    salaryRange: '6-10 LPA',
    applyUri: 'https://oracle.taleo.net/junior-backend-developer',
    description:
      'Contribute to backend services within Oracle’s cloud products.\nYou will operate within established patterns and deployment cycles.\nIdeal for developers who prefer long-term ownership of services.',
  },
  {
    id: 'job-55',
    title: 'Data Analyst Intern',
    company: 'Zoho',
    location: 'Chennai, Tamil Nadu',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['SQL', 'Excel', 'Reports'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://careers.zoho.com/jobs/data-analyst-intern',
    description:
      'Assist product managers with user adoption and retention reports.\nYou will maintain recurring dashboards and improve them over time.\nGood for interns who like calm, repeatable reporting work.',
  },
  {
    id: 'job-56',
    title: 'Python Developer (Fresher)',
    company: 'Freshworks',
    location: 'Chennai, Tamil Nadu',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Flask', 'REST'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '3-5 LPA',
    applyUri: 'https://www.freshworks.com/company/careers/python-developer-fresher',
    description:
      'Work on internal CRM integrations and smaller backend services.\nYou will receive clear tickets with minimal ambiguity.\nIdeal for freshers who prefer stable, well-scoped projects.',
  },
  {
    id: 'job-57',
    title: 'React Developer (1-3)',
    company: 'Infosys',
    location: 'Pune, Maharashtra',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'REST'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '6-10 LPA',
    applyUri: 'https://careers.infosys.com/react-developer',
    description:
      'Develop front-end modules for enterprise dashboards used by clients.\nYou will integrate with APIs and follow strict UI guidelines.\nsuited for engineers who appreciate consistency and clear UX standards.',
  },
  {
    id: 'job-58',
    title: 'SDE Intern',
    company: 'Capgemini',
    location: 'Mumbai, Maharashtra',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Java', 'Spring', 'SQL'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.capgemini.com/in-en/careers/sde-intern',
    description:
      'Work with project teams on internal tools and automation.\nYou will start with documentation and gradually move into implementation.\nGood for interns who favour gradual responsibility.',
  },
  {
    id: 'job-59',
    title: 'Graduate Engineer Trainee',
    company: 'Swiggy',
    location: 'Bangalore, Karnataka',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Kotlin', 'SQL'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '6-10 LPA',
    applyUri: 'https://careers.swiggy.com/jobs/graduate-engineer-trainee',
    description:
      'Join the early talent program and work on logistics or customer experience teams.\nYou will focus on shipping stable, incremental changes.\nIdeal for graduates seeking structured mentorship.',
  },
  {
    id: 'job-60',
    title: 'Frontend Intern',
    company: 'PhonePe',
    location: 'Bangalore, Karnataka',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'CSS'],
    source: 'LinkedIn',
    postedDaysAgo: 8,
    salaryRange: '₹15k-40k/month Internship',
    applyUri: 'https://www.phonepe.com/careers/frontend-intern',
    description:
      'Help maintain and refine internal web tools for support teams.\nYou will be guided through code reviews and pairing sessions.\nBest for interns who like quiet, consistent progress over time.',
  },
]

